version: "3.9"

services:
  app:
    container_name: hongyi_apache-php7.4
    restart: "no"
    build: 
      context: ./containers/apache_php
      dockerfile: Dockerfile
    networks:
      hongyi_prob:
        ipv4_address: 192.168.89.3
    extra_hosts: 
      - "hcprob.vm:127.0.0.1"
    volumes:
      - ../application:/var/www/html
      - ~/.composer:/.composer
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /tmp:mode=1777
    ports:
      - "127.0.0.1:80:80"
  db:
    container_name: hongyi_mysql-5.7
    restart: "no"
    build:
      context: ./containers/mysql5.7
      dockerfile: Dockerfile
    networks:
      hongyi_prob:
        ipv4_address: 192.168.89.2
    volumes:
      - ../mysql5.7/db-data:/var/lib/mysql:delegated
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
networks:
  hongyi_prob:
    name: hc_prob_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.89.0/24