home:
  path: /{_locale}
  controller: App\Controller\PortalController::index
  defaults:
    _locale: en
  requirements:
    _locale: en|de

imprint:
  path:
    en: /en/imprint
    de: /de/impressum
  controller: App\Controller\ImprintController::index


users:
   path: /users
   controller: App\Controller\UsersController::index

