home:
  path: /{_locale}
  controller: App\Controller\PortalController::index
  defaults:
    _locale: en
  requirements:
    _locale: "^[a-zA-Z]{2}$"

imprint_standard:
  path: /{_locale}/imprint
  controller: App\Controller\ImprintController::index

admin:
  path: /admin
  controller: App\Controller\AdminController::index

admin_portal:
  path: /admin/portal
  controller: App\Controller\AdminController::portal

admin_portal_edit:
  path: /admin/portal/edit/{locale}
  controller: App\Controller\AdminController::edit

admin_portal_del:
  path: /admin/portal/delete/{locale}
  controller: App\Controller\AdminController::delete

admin_page:
  path: /admin/page
  controller: App\Controller\PageController::index

admin_page_del:
  path: /admin/page/delete/{pageid}
  controller: App\Controller\PageController::delete

admin_page_edit:
  path: /admin/page/edit/{pageid}
  controller: App\Controller\PageController::edit


imprintApi:
  path: /{_locale}/imprint.json
  controller: App\Controller\ImprintController::jsonFormat


users:
   path: /users
   controller: App\Controller\UsersController::index

